#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 800
#define DEBUG_CURSOR 1


#define MAX_MAP_NODES 20
#define MAP_NODE_COLOR RAYWHITE
#define MAP_NODE_RADIUS 6
#define HOVERED_NODE_COLOR BLUE

#define MAX_MAP_SECTORS 20
#define MAP_SECTOR_THICKNESS 3
#define MAP_SECTOR_COLOR RAYWHITE

#define SERVER_TO_PLAYER_MOVE_SPEED_SCALING 0.5f
#define NUM_PLAYERS_TO_START_SERVER 2

#endif
